In [1]:
import numpy as np

In [13]:
#new array with 2 dimension integer datatype
myarr = np.array([[1,2,3,4]], np.int8)

In [21]:
# 1 dim array
myarr1dim = np.array([1,2,3,4], np.int8)

In [24]:
myarr1dim[1]


2

In [25]:
#access element
myarr

array([[1, 2, 3, 4]], dtype=int8)

In [27]:
#access element
myarr1dim[1]

2

In [28]:
myarr.shape

(1, 4)

In [29]:
myarr.dtype

dtype('int8')

In [36]:
myarr.size

4

In [37]:
myarr.shape

(1, 4)

In [30]:
#change value in arry
myarr[0,1] = 45

In [31]:
myarr

array([[ 1, 45,  3,  4]], dtype=int8)

In [ ]:
#Conversion from other Python structures (i.e. lists and tuples)
#Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
#Replicating, joining, or mutating existing arrays
#Reading arrays from disk, either from standard or custom formats
#Creating arrays from raw bytes through the use of strings or buffers
#Use of special library functions (e.g., random)

In [38]:
nyone = np.ones((5,5))

In [39]:
nyone

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
nyzero = np.zeros((5,5))

In [45]:
nyzero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
arange = np.arange(15)

In [47]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
#linear space
lspace = np.linspace(1,5,12)

In [49]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [58]:
emp = np.empty((10,10))

In [59]:
emp

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
emp_like = np.empty_like(emp)

In [62]:
emp_like

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
# give array of 10 x 10 of identity
ide =  np.identity(10)

In [64]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [77]:
arr = np.arange(99)

In [79]:
arr = arr.reshape(3,33)

In [82]:
# design to 1d array
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [84]:
ar = np.array([[1,2,3],[4,5,6],[7,0,1]])

In [85]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [97]:
# axis = 0 is for row (goes to down) 
ar.sum(axis=0)

array([12,  7, 10])

In [98]:
 # axis = 1 is for column (goes to left to right) 
ar.sum(axis=1)

array([ 6, 15,  8])

In [100]:
#Transpose the array (row to col and col to row)
ar.T

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [104]:
#flat the array, it returns iterator
ar.flat

In [105]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
0
1


In [109]:
#check dimension
ar.ndim

2

In [110]:
#nos of elements. this is attribute, when it ends with (), it become method
ar.size

9

In [112]:
#tell how much bytes consume in this array
ar.nbytes

36

In [120]:
o = np.array([1,2,45,65,2])

In [121]:
# returns the index of max value in index
o.argmax()

3

In [122]:
o.argmin()

0

In [127]:
#returns sort indices
o.argsort()

array([0, 1, 4, 2, 3], dtype=int64)

In [129]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [130]:
# in 2 dims array, if we use argmin or max, it will first sort the array and return the index
ar.argmax()

6

In [133]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [134]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [135]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

In [140]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [0],
       [1]])

In [143]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 0, 1])

In [146]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 0, 1])

In [147]:
# matrix opertion
ar2 = ar.copy()

In [148]:
ar + ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  0,  2]])

In [149]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [150]:
ar * ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  0,  1]])

In [152]:
ar * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  0,  2]])

In [153]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 0.        , 1.        ]])

In [154]:
ar.min()

0

In [155]:
ar.max()

7

In [156]:
ar.sum()

29

In [160]:
# find the element. it return tuple array
type(np.where(ar>5))

tuple

In [162]:
# return non-zero element
np.count_nonzero(ar)

8

In [164]:
#return non-zero index, we have zero at 2,2
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 2], dtype=int64))

In [166]:
import sys

In [168]:
# size compaision
py_ar =  [0,4,34,54]

In [169]:
np_ar = np.array(py_ar)

In [175]:
# will tell size of 1 element * len of array
sys.getsizeof(1) * len(py_ar)

112

In [178]:
# itemsize is one attribute * nos of attribute
np_ar.itemsize * len(py_ar)

16

In [184]:
ar.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [189]:
p = ar.flat

1
2
3
4
5
6
7
0
1


# * get details from numpy library attribute and method*

From Copy

In [194]:
# difference between list and array (array can contain only same data type whereas list can contain anything)
# array consume less memory
# array are faster
# array are coll of elements of same datatype, can be 1d, 2d, 3d etc

In [195]:
#creating numpy array

In [211]:
array = np.array([2,5,10,45])

In [212]:
array

array([ 2,  5, 10, 45])

In [213]:
arange = np.arange(15)

In [214]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [215]:
zeros = np.zeros(10)

In [216]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [217]:
once = np.ones(10)

In [218]:
once

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [230]:
# start, stop, numbersReqd
linspace = np.linspace(1,100,10)

In [231]:
linspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [236]:
# 1 row with 5 colums
random = np.random.rand(5)

In [240]:
random

array([0.16370589, 0.77955835, 0.32705325, 0.42011046, 0.50588288])

In [238]:
# 4 rows, 5 colums
random1 = np.random.rand(4,5)

In [239]:
random1

array([[0.58900886, 0.45319406, 0.0139275 , 0.5474435 , 0.53144667],
       [0.81568413, 0.15452264, 0.16480767, 0.43076635, 0.90269263],
       [0.83068936, 0.69693693, 0.61810482, 0.5675359 , 0.63685843],
       [0.99309607, 0.98038572, 0.93280553, 0.79354298, 0.60591934]])

In [254]:
# return s sample from the "sample normal" distribution
randomint = np.random.randn(4,5)

In [265]:
randomint

array([[-0.07853581,  1.55706175, -0.00386214, -0.54952439,  0.11777663],
       [-0.37838202, -0.31801384, -1.10531604, -0.89342005,  1.02152345],
       [ 0.19121633, -0.78874282,  0.55053123,  0.7561978 ,  0.24132183],
       [ 0.86948739,  0.18747214, -0.15840366, -0.19957245,  1.40780978]])

# attributes

In [297]:
# 1d, 2d, 3d
a = np.array([1,2,3,4])
b = np.array([[1,2],[3,4],[6,8]])
c = np.array([[[1,2,3]],[[4,5,6]],[[7,0,1]]])

In [302]:
print(a.ndim, b.ndim, c.ndim)

1 2 3


In [303]:
print(a.shape, b.shape, c.shape)

(4,) (3, 2) (3, 1, 3)


In [304]:
print(a.size, b.size, c.size)

4 6 9


In [305]:
print(a.dtype, b.dtype, c.dtype)

int32 int32 int32


In [310]:
# size in bytes in each element of array
print(a.itemsize, b.itemsize, c.itemsize)

4 4 4


In [311]:
c

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 0, 1]]])

In [ ]:
# datatype can be used as function
o = np.array([1,2,3],dtype='f')

In [327]:
# can change type of array by typecasting 
tc = np.zeros(5) # default have float
print(tc.dtype)

float64


In [328]:
tc.astype('int8')
tc

array([0., 0., 0., 0., 0.])

In [330]:
x = np.array([1, 2, 2.5])
x

array([1. , 2. , 2.5])

In [333]:
x.astype(int)

array([1, 2, 2])

In [334]:
x

array([1. , 2. , 2.5])

In [339]:
a

array([1, 2, 3, 4])

In [343]:
a[-2]

3

In [344]:
b

array([[1, 2],
       [3, 4],
       [6, 8]])

In [348]:
# first value for row, another rows for column
b[1][0]

3

In [349]:
b[-1][-1]

8

In [359]:
c

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 0, 1]]])

In [355]:
c[1][0][0]

4

In [377]:
# easy explaination https://www.youtube.com/watch?v=rITvjYY6D2g
dim3ar = np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]]])

In [378]:
dim3ar

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 5, 4]]])

In [402]:
dim3ar[0][1][1]

5

In [401]:
#slicing of 1d array a[start:end:step]
#slicing of 2d array a[start:end:step,start:end:step]
#slicing of 2d array a[start:end:step,start:end:step,start:end:step]
# https://www.youtube.com/watch?v=fIXh-gmR7mQ
b

array([[1, 2],
       [3, 4],
       [6, 8]])

In [413]:
dim3ar

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 5, 4]]])

In [412]:
dim3ar[0:1,1:,0:1]

array([[[4]]])

In [404]:
dim3ar[:,:,1]

array([[2, 5],
       [2, 5]])

In [409]:
dim3ar[0:1,0:1,0:1]

array([[[1]]])

In [416]:
# easy explaination https://www.youtube.com/watch?v=rITvjYY6D2g
dim3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [417]:
dim3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [421]:
dim3ar[0:1,0:1,1:2]

array([[[2]]])

In [447]:
# advance indexing
t = np.arange(10,20)
print(t)
index = np.array([1,4,5])
print(index)
print(t[index])


[10 11 12 13 14 15 16 17 18 19]
[1 4 5]
[11 14 15]


In [451]:
# boolena indexing (get value grater than 1)
boolen = np.array([[1,-2,3],[4,-2,3]])
boolen[boolen>1]

array([3, 4, 3])

In [461]:
# arthmatic operation 1)scaler 2)b/w array (add,div,mul etc)
c = np.array([1,2,3,4])
print(a)
a+3
a-1
a*3
a/3

[1 2 3 4]


array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [480]:
# can also used arthmetic operation by function
x = np.array([1,2,3,4])
y = np.array([11,11,11,11])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.mod(x,y))
print(np.power(x,y))


[12 13 14 15]
[-10  -9  -8  -7]
[11 22 33 44]
[0.09090909 0.18181818 0.27272727 0.36363636]
[1 2 3 4]
[      1    2048  177147 4194304]
